version: "3.9"
services:
  db:
    image: postgres:15          # ou outra versão de sua preferência
    container_name: myDB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
